"""Run the step 2 validation checks and write docs/VALIDATION.md."""

import argparse
import time
from pathlib import Path

import jsbsim

from flightsim.analysis.validation import format_value, load_validation_config, run_checks
from flightsim.core import aircraft_hash


def status(c) -> str:
    if c.passed:
        return "PASS" if not c.known_deviation else "PASS (was known deviation)"
    return "KNOWN DEVIATION" if c.known_deviation else "FAIL"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", nargs="?", default="configs/validation/c172p.yaml")
    parser.add_argument("--out", default="docs/VALIDATION.md")
    args = parser.parse_args()

    cfg = load_validation_config(args.config)
    t0 = time.perf_counter()
    checks = run_checks(cfg)
    wall = time.perf_counter() - t0

    for c in checks:
        print(f"{status(c):16s} {c.id:40s} model {format_value(c.model):>8s} {c.unit:12s} ref {c.reference:22s} allowed {c.allowed}")
    counts = {s: sum(status(c) == s for c in checks) for s in ("PASS", "KNOWN DEVIATION", "FAIL")}
    print(f"\n{len(checks)} checks in {wall:.1f} s: " + ", ".join(f"{n} {s.lower()}" for s, n in counts.items()))

    lines = [
        "# Validation report",
        "",
        f"Generated by `scripts/validate.py` from `{args.config}`. Do not edit by hand.",
        "",
        f"- Aircraft: `{cfg['aircraft']}`, JSBSim {jsbsim.__version__}, aircraft hash `{aircraft_hash(cfg['aircraft'])[:12]}`",
        f"- Result: {counts['PASS']} pass, {counts['KNOWN DEVIATION']} known deviations, {counts['FAIL']} fail",
        "- Sources and how values were read: `docs/REFERENCES.md`",
        "",
        "| Status | Check | Model | Reference | Allowed | Source |",
        "|---|---|---|---|---|---|",
    ]
    for c in checks:
        lines.append(f"| {status(c)} | {c.description} | {format_value(c.model)} {c.unit} | {c.reference} | {c.allowed} | {c.source} |")
    deviations = [c for c in checks if c.known_deviation]
    if deviations:
        lines += ["", "## Known deviations", ""]
        lines += [f"- **{c.id}:** {c.known_deviation}" for c in deviations]
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
